language: node_js
node_js:
- '4.1'
before_script:
- npm install -g gulp
script: gulp
after_success:
- bash .publish-gh-pages.sh
before_install:
- openssl aes-256-cbc -K $encrypted_a5b8ed97d480_key -iv $encrypted_a5b8ed97d480_iv
  -in deploy_key.enc -out deploy_key -d
